import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

console.log('--- Verifying NEXA One Phase 13 / Production Polish & Vercel Readiness ---');

let passed = 0;
let failed = 0;

function assert(condition, message) {
  if (condition) {
    console.log(`✓ ${message}`);
    passed++;
  } else {
    console.error(`✗ ${message}`);
    failed++;
  }
}

// 1. Centralized dataset links configuration
const datasetLinksJs = fs.readFileSync(path.join(__dirname, 'src/config/datasetLinks.js'), 'utf-8');
assert(datasetLinksJs.includes('2PACX-1vQ6Beq43sYS4CsfiGT0R1xe7gJj9fkVvp3dURrOzfX_6B6zII9nGVnDplUdxEbzGg'), 'Advertising Google Sheet link matches exact approved URL');
assert(datasetLinksJs.includes('2PACX-1vSr2F0Q8mGgj71aMYSMhV-I7A7r7WxF_jL7YKZ0qtse-ZruIPajLSWiqSgT7GFAsw'), 'Customer Research Google Sheet link matches exact approved URL');
assert(datasetLinksJs.includes('2PACX-1vTva6_i5TZp9R4nRlCEhtzY2TjViii2msFSi34o8lwdyf4GLiTV4BQF-TMf3knEJbIOKTfB03q_2f85'), 'Market & Macro Google Sheet link matches exact approved URL');

// 2. Report Footer Structure & Identity (Phase 13B: Minimal, Author-Signed Footer)
const footerJsx = fs.readFileSync(path.join(__dirname, 'src/components/report/ReportFooter.jsx'), 'utf-8');
const footerCss = fs.readFileSync(path.join(__dirname, 'src/components/report/ReportFooter.css'), 'utf-8');

assert(footerJsx.includes('NEXA One') && footerJsx.includes('Business Analytics Report'), 'Footer identifies product as NEXA One Business Analytics Report');
assert(footerJsx.includes('Nikhil Kumar Shah'), 'Footer clearly attributes author as Nikhil Kumar Shah');
assert(footerJsx.includes('Prepared by'), 'Footer includes "Prepared by" author signature line');
assert(!footerJsx.includes('GTA 2.0') && !footerJsx.includes('Grand Theft Analytica'), 'Footer contains no GTA 2.0 branding');
assert(!footerJsx.includes('IIT Madras') && !footerJsx.includes('Business.io'), 'Footer contains no IIT Madras or Business.io branding');
assert(!footerJsx.includes('Case Competition') && !footerJsx.includes('Competition Evaluation'), 'Footer contains no competition evaluation labels');
assert(!footerJsx.includes('Generated by AI') && !footerJsx.includes('Created with AI') && !footerJsx.includes('Antigravity'), 'Footer contains no AI generation tags');
assert(footerJsx.includes('rel="noopener noreferrer"') && footerJsx.includes('target="_blank"'), 'External dataset links open safely in new tab');
assert(footerJsx.includes('© 2026 Nikhil Kumar Shah'), 'Footer bottom bar includes approved copyright signature');
assert(footerJsx.includes('RESOURCES') && footerJsx.includes('UTILITY'), 'Footer has compact 3-zone structure (Identity, Resources, Utility)');
assert(footerJsx.includes('scrollToTop') || footerJsx.includes('Back to top'), 'Footer includes Back to top utility control');
assert(!footerJsx.includes('reportSections.map'), 'Footer does not repeat entire 9-section sitemap');
assert(footerCss.includes('footer-main-grid') && footerCss.includes('@media (max-width: 640px)'), 'Footer CSS has responsive layout and mobile stacking');

// 3. Contextual Dataset Source Links
const advViewJsx = fs.readFileSync(path.join(__dirname, 'src/views/advertising/AdvertisingSalesView.jsx'), 'utf-8');
const custViewJsx = fs.readFileSync(path.join(__dirname, 'src/views/customer/CustomerDriversView.jsx'), 'utf-8');
const marketViewJsx = fs.readFileSync(path.join(__dirname, 'src/views/market/MarketMacroView.jsx'), 'utf-8');
const sourcesViewJsx = fs.readFileSync(path.join(__dirname, 'src/views/methodology/MethodologySourcesView.jsx'), 'utf-8');

assert(advViewJsx.includes('DatasetSourceLink') && advViewJsx.includes("datasetKey=\"advertising\""), 'Section 03 includes contextual Advertising Dataset link');
assert(custViewJsx.includes('DatasetSourceLink') && custViewJsx.includes("datasetKey=\"customerResearch\""), 'Section 05 includes contextual Customer Research Dataset link');
assert(marketViewJsx.includes('DatasetSourceLink') && marketViewJsx.includes("datasetKey=\"marketMacro\""), 'Section 06 includes contextual Market & Macro Dataset link');
assert(sourcesViewJsx.includes('DatasetSourceLink') && sourcesViewJsx.includes('ms-published-workbooks'), 'Section 09 includes Published Analytical Datasets panel');

// 4. Vercel Configuration & Serverless Architecture
assert(fs.existsSync(path.join(rootDir, 'api/index.py')), 'api/index.py entrypoint exists at project root');
const apiIndexPy = fs.readFileSync(path.join(rootDir, 'api/index.py'), 'utf-8');
assert(apiIndexPy.includes('from backend.app.main import app'), 'api/index.py imports and exports FastAPI app instance');

assert(fs.existsSync(path.join(rootDir, 'vercel.json')), 'vercel.json exists at project root');
const vercelJson = fs.readFileSync(path.join(rootDir, 'vercel.json'), 'utf-8');
assert(vercelJson.includes('frontend/dist'), 'vercel.json specifies frontend/dist as outputDirectory');
assert(vercelJson.includes('/index.html') && vercelJson.includes('destination'), 'vercel.json routes SPA fallbacks cleanly to /index.html');

// 5. Documentation & Environment Configuration
assert(fs.existsSync(path.join(rootDir, '.env.example')), '.env.example exists at project root');
const envExample = fs.readFileSync(path.join(rootDir, '.env.example'), 'utf-8');
assert(envExample.includes('VITE_API_BASE_URL') && envExample.includes('NEXA_DATA_DIR'), '.env.example documents optional variables');

assert(fs.existsSync(path.join(rootDir, 'DEPLOYMENT.md')), 'DEPLOYMENT.md exists at project root');
const deploymentMd = fs.readFileSync(path.join(rootDir, 'DEPLOYMENT.md'), 'utf-8');
assert(deploymentMd.includes('vercel deploy --prod') && deploymentMd.includes('Troubleshooting'), 'DEPLOYMENT.md contains production commands and troubleshooting guide');

assert(fs.existsSync(path.join(rootDir, 'README.md')), 'README.md exists at project root');
const readmeMd = fs.readFileSync(path.join(rootDir, 'README.md'), 'utf-8');
assert(readmeMd.includes('is an interactive analytical report combining statistical advertising analysis'), 'README.md uses approved project description');
assert(!readmeMd.includes('GTA 2.0 submission') && !readmeMd.includes('competition dashboard'), 'README.md contains no competition or submission wording');

// 6. HTML Metadata
const indexHtml = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf-8');
assert(indexHtml.includes('<title>NEXA One</title>') || indexHtml.includes('NEXA One — Business Analytics Report'), 'index.html has approved title tag');
assert(indexHtml.includes('meta name="description"'), 'index.html has production meta description');

// 7. Executive Overview Factual Precision Patch
const execOverviewJsx = fs.readFileSync(path.join(__dirname, 'src/views/overview/ExecutiveOverviewView.jsx'), 'utf-8');
assert(execOverviewJsx.includes('the print coefficient is not statistically significant'), 'Print significance phrasing updated');
assert(execOverviewJsx.includes('Observed sales variation explained by model'), 'Model fit KPI subtext updated');
assert(execOverviewJsx.includes('India TWS remained broadly flat in 2025, while Q4 recorded 12% YoY growth.'), 'India TWS signal title updated');
assert(execOverviewJsx.includes('Revenue increased despite a decline in quarterly shipments, consistent with premiumization and a higher-value market mix.'), 'Premiumization description updated');
assert(execOverviewJsx.includes('Global OWS +12% YoY in Q2 2026'), 'OWS signal title updated to Global OWS');
assert(execOverviewJsx.includes('Global trade inflation 3.6% → ~5%'), 'Trade inflation signal title updated to Global');
assert(execOverviewJsx.includes('External research indicates broadly flat volume in several observed TWS segments') && execOverviewJsx.includes('alongside premiumization and emerging open-ear alternatives.'), 'Market context finding updated');
assert(execOverviewJsx.includes('The evidence supports a selective allocation approach: maintain attention on TV and social media, reassess the role of print, and use incremental testing to validate future budget changes.'), 'Strategic direction statement updated');
assert(execOverviewJsx.includes('Communicate Recurring Product Value') && execOverviewJsx.includes('recurring considerations identified in the reviewed research'), 'Customer messaging and recurring considerations updated');
assert(execOverviewJsx.includes('Device and ecosystem compatibility') && execOverviewJsx.includes('Build, materials and product appearance'), 'Q3 factor cards simplified');

console.log(`\nPhase 13 Check: ${passed} passed, ${failed} failed.`);
if (failed > 0) {
  process.exit(1);
}
